services:
  recipe-server:
    image: python:3.13-slim
    command: python -m http.server 8000
    working_dir: /recipes
    volumes:
      - ./smoothie-database:/recipes
    ports:
      - "8000:8000"

  smoothie-app:
    build:
      context: .
      dockerfile: Dockerfile_Clean
    command: http://recipe-server:8000/tropical_paradise.txt
    depends_on:
      - recipe-server